- name: Install packages
  apt:
    name:
      - htop
      - mc
      - tmux
      - guake

- name: Start guake during system startup
  shell:
    "cp /usr/share/applications/guake.desktop /etc/xdg/autostart/"